# https://alacritty.org/config-alacritty.html

[general]
import = [ "~/.config/alacritty/theme.toml" ]

[window]
padding = { x = 5, y = 5 }
dynamic_padding = true
decorations = "Buttonless"
startup_mode = "Maximized"
option_as_alt = "Both"

[font]
size = 15
normal = { family = "JetBrainsMonoNL Nerd Font Mono" }

[cursor]
style = { blinking = "On" }
blink_interval = 500
blink_timeout = 0

[mouse]
hide_when_typing = true
