#!/bin/sh

set -euf

# git
dir="$HOME/.config/git"
mkdir -p "$dir"
ln -sf "$PWD/gitconfig" "$dir/config"
ln -sf "$PWD/gitignore" "$dir/ignore"

# fish
dir="$HOME/.config/fish"
mkdir -p "$dir"
ln -sf "$PWD/config.fish" "$dir"
ln -sf "$PWD/fish_plugins" "$dir"

# starship
ln -sf "$PWD/starship.toml" "$HOME/.config"

# nvim
dir="$HOME/.config/nvim"
mkdir -p "$dir"
ln -sf "$PWD/init.lua" "$dir"

# tmux
dir="$HOME/.config/tmux"
mkdir -p "$dir"
ln -sf "$PWD/tmux.conf" "$dir"

# htop
dir="$HOME/.config/htop"
mkdir -p "$dir"
ln -sf "$PWD/htoprc" "$dir"

# editorconfig
ln -sf "$PWD/.editorconfig" "$HOME"

# Paneru
dir="$HOME/.config/paneru"
mkdir -p "$dir"
ln -sf "$PWD/paneru.toml" "$dir"

# Aerospace
dir="$HOME/.config/aerospace"
mkdir -p "$dir"
ln -sf "$PWD/aerospace.toml" "$dir"

# Alacritty
dir="$HOME/.config/alacritty"
mkdir -p "$dir"
ln -sf "$PWD/alacritty.toml" "$dir"
if [ ! -d "$dir/themes" ]; then
    git clone https://github.com/alacritty/alacritty-theme "$dir/themes"
fi
cp "$dir/themes/themes/alabaster.toml" "$dir/theme.toml"
cp "$dir/themes/themes/alabaster_dark.toml" "$dir/theme_alt.toml"

# Ghostty
dir="$HOME/.config/ghostty"
mkdir -p "$dir"
ln -sf "$PWD/config.ghostty" "$dir/config"
if [ ! -d "$dir/shaders" ]; then
    git clone https://github.com/sahaj-b/ghostty-cursor-shaders "$dir/shaders"
fi

# LibreWolf
dir="$HOME/.librewolf"
mkdir -p "$dir"
ln -sf "$PWD/librewolf.overrides.cfg" "$dir"

# Sublime Text
dir="$HOME/Library/Application Support/Sublime Text/Packages/User"
mkdir -p "$dir"
ln -sf "$PWD/Preferences.sublime-settings" "$dir"

# /usr/local/bin
sudo ln -sf "$PWD/bin/toggle_dark_mode" /usr/local/bin

if [ "$(uname)" = "Darwin" ]; then
    /opt/homebrew/bin/brew bundle install --file=Brewfile

    if [ "$SHELL" != "/opt/homebrew/bin/fish" ]; then
        sudo chsh -s /opt/homebrew/bin/fish "$USER"
    fi

    # Karabiner-Elements
    dir="$HOME/.config/karabiner"
    mkdir -p "$dir"
    ln -sf "$PWD/karabiner.json" "$dir"
fi
