#!/bin/sh

set -eu

# git
dir="$HOME/.config/git"
mkdir -p "$dir"
ln -sf "$PWD/gitconfig" "$dir/config"
ln -sf "$PWD/gitignore" "$dir/ignore"

# fish
dir="$HOME/.config/fish"
mkdir -p "$dir"
ln -sf "$PWD/config.fish" "$dir"
ln -sf "$PWD/fish_plugins" "$dir"

# nvim
dir="$HOME/.config/nvim"
mkdir -p "$dir"
ln -sf "$PWD/init.lua" "$dir"

# tmux
dir="$HOME/.config/tmux"
mkdir -p "$dir"
ln -sf "$PWD/tmux.conf" "$dir"

# htop
dir="$HOME/.config/htop"
mkdir -p "$dir"
ln -sf "$PWD/htoprc" "$dir"

# editorconfig
ln -sf "$PWD/.editorconfig" "$HOME"

# /usr/local/bin
for file in bin/*; do
    sudo ln -sf "$PWD/$file" /usr/local/bin
done

# Alacritty
dir="$HOME/.config/alacritty"
mkdir -p "$dir"
ln -sf "$PWD/alacritty.toml" "$dir"

# LibreWolf
dir="$HOME/.librewolf"
mkdir -p "$dir"
ln -sf "$PWD/librewolf.overrides.cfg" "$dir"

# Sublime Text
dir="$HOME/Library/Application Support/Sublime Text/Packages/User"
mkdir -p "$dir"
ln -sf "$PWD/Preferences.sublime-settings" "$dir"

# Obsidian
dir="$HOME/wiki/.obsidian"
mkdir -p "$dir/snippets"
for file in obsidian/*.json; do
    ln -sf "$PWD/$file" "$dir"
done
ln -sf "$PWD/obsidian/styles.css" "$dir/snippets"

install_terminal_themes() {
    light_theme="catppuccin-latte"
    dark_theme="catppuccin-frappe"

    dir="$HOME/.config/alacritty"
    curl -so "$dir/$light_theme.toml" https://raw.githubusercontent.com/catppuccin/alacritty/main/catppuccin-latte.toml
    curl -so "$dir/$dark_theme.toml" https://raw.githubusercontent.com/catppuccin/alacritty/main/catppuccin-frappe.toml
    echo "import = [ \"$dir/$light_theme.toml\" ]" > "$dir/theme.toml"

    dir="$HOME/.config/bat"
    mkdir -p "$dir/themes"
    curl -so "$dir/themes/$light_theme.tmTheme" https://raw.githubusercontent.com/catppuccin/bat/main/Catppuccin-latte.tmTheme
    curl -so "$dir/themes/$dark_theme.tmTheme" https://raw.githubusercontent.com/catppuccin/bat/main/Catppuccin-frappe.tmTheme
    echo "--theme=$light_theme" > "$dir/config"
    bat cache --build > /dev/null
}

install_terminal_themes

# macOS
if [ "$(uname)" = "Darwin" ]; then
    cd macos
    # TODO: brew
    # TODO: defaults

    if [ "$SHELL" != "/opt/homebrew/bin/fish" ]; then
        chsh --shell /opt/homebrew/bin/fish
    fi

    # Karabiner-Elements
    dir="$HOME/.config/karabiner/assets/complex_modifications"
    mkdir -p "$dir"
    ln -sf "$PWD/karabiner.json" "$dir"

    # launchd
    # NOTE: symlinks do not work on Sonoma
    for file in LaunchAgents/*.plist; do
        sed "s|\$HOME|$HOME|" "$file" > "$HOME/Library/$file"
    done

    for file in LaunchDaemons/*.plist; do
        sudo cp -f "$file" "/Library/LaunchDaemons"
    done
fi
