# https://github.com/rvaiya/keyd#quickstart

[ids]
*

[main]
capslock = overload(control, esc)
enter = overload(control, enter)
leftshift = overload(shift, f13)
rightshift = overload(shift, f14)

[control]
h = left
j = down
k = up
l = right

[alt]
left = C-left
right = C-right
backspace = C-backspace

[control+alt]
h = C-left
l = C-right

[meta]
c = C-insert
v = S-insert
x = S-delete
a = C-a
f = C-f
r = C-r
t = C-t
w = C-w
z = C-z
0 = C-0
- = C--
= = C-=
, = C-,
left = home
right = end
backspace = C-u

[meta+control]
h = home
l = end
