tap "homebrew/autoupdate"
tap "homebrew/bundle"
tap "homebrew/services"
# Clone of cat(1) with syntax highlighting and Git integration
brew "bat"
# Simple, fast and user-friendly alternative to find
brew "fd"
# User-friendly command-line shell for UNIX-like operating systems
brew "fish"
# Command-line fuzzy finder written in Go
brew "fzf"
# GitHub command-line tool
brew "gh"
# GNU implementation of the famous stream editor
brew "gnu-sed"
# Open source programming language to build simple/reliable/efficient software
brew "go"
# Fast linters runner for Go
brew "golangci-lint"
# Language server for the Go language
brew "gopls"
# Improved top (interactive process viewer)
brew "htop"
# Simple terminal UI for git commands
brew "lazygit"
# Ambitious Vim-fork focused on extensibility and agility
brew "neovim"
# Static analysis and lint tool, for (ba)sh scripts
brew "shellcheck"
# Simplified and community-driven man pages
brew "tldr"
# Terminal multiplexer
brew "tmux"
# Display directories as trees (with optional color/HTML output)
brew "tree"
# GPU-accelerated terminal emulator
cask "alacritty"
# Enable Windows-like alt-tab
cask "alt-tab"
# Utility to show apps badges from the dock in the menu bar
cask "doll"
cask "font-jetbrains-mono-nerd-font"
# Keyboard customiser
cask "karabiner-elements"
# Move and resize windows using keyboard shortcuts or snap areas
cask "rectangle"
